### ISSUE TITLE
Empty bitmask inside DefinitionsElement::Bitmask

### ISSUE THREAD

**Issue by MaikKlein** [krolli/vk-parse#1]
```
....
    Bitmask {
        name: "VkFenceImportFlags",
        notation: None,
        basetype: "VkFlags",
        enumref: Some(
            "VkFenceImportFlagBits"
        )
    },
    Bitmask {
        name: "",
        notation: None,
        basetype: "",
        enumref: None
    },
    Bitmask {
        name: "VkSurfaceCounterFlagsEXT",
        notation: None,
        basetype: "VkFlags",
        enumref: Some(
            "VkSurfaceCounterFlagBitsEXT"
        )
    },
....
```
There is an empty bitmask inside DefinitionsElement::Bitmask. Not a high priority for me, I just wanted to let you know.

**Comment by krolli** [comment]
Yeah, seems to be caused by aliases that were added with vulkan 1.1 and I don't think there is a way to represent them in structures from vkxml. I think the safest thing to do for now would be to just filter them out.

**Comment by krolli** [comment]
I added filtering of aliases for bitmasks, commands and constants. Since they are just another name for existing identifiers, there should always be fully defined alternative (eg. VkFenceImportFlagsKHR is an alias of VkFenceImportFlags which is fully defined).

Hopefully, once #2 has been dealt with, there will be better solution to this available. I will leave this open until then. If you happen to run into more such cases, let me know.

**Comment by krolli** [comment]
With IR based on rnc schemas exposed, we can now provide all information in xml without having to deal with vkxml crate being stuck in the past.
