### ISSUE TITLE
Crate activity and maintenance

### ISSUE THREAD

**Issue by MarijnS95** [krolli/vk-parse#18]
Hi @krolli!

We're curious whether you're still actively monitoring/maintaining this crate. It is being used in [Ash](https://github.com/MaikKlein/ash) and we'd like to parse some new fields for which I have filed #17 but have yet to receive a response. Given that this repo hasn't seen any commits for the better part of a year I thought I'd ask formally in an issue :slightly_smiling_face: 

Additionally I'm "closely" following what's happening around `IntoIter` for arrays and accidentally stumbled upon this crate [failing to compile](https://crater-reports.s3.amazonaws.com/pr-65819/try%234a04890980766cc79878135f5ade8c0c4321e943/gh/krolli.vk-parse/log.txt) due to outdated dependencies: https://crater-reports.s3.amazonaws.com/pr-65819/index.html. #17 performs a `cargo update` that should (at least) update `ring` to a version that does not suffer from this issue.

**Comment by krolli** [comment]
Hi, I've been rather busy lately with other things and my day-to-day work does not involve github. It also doesn't help that github didn't send me any notifications about your pull request or other things. This is the first notification I got in several months. :(

I have set up travis-ci job that should notify me when new version of vulkan XML contains unrecognized elements or attributes. That CI job occasionally fails due to some download errors, but I have not seen a failure due to new elements or attributes, so if there are new ones, I will have to check why it wasn't caught earlier as well (in addition to adding support for them).

Thanks for bringing this up, I will try to take a look at all of this (pull request, missing parts of xml, CI not detecting this, etc.). I definitely don't think of the project as dead, I just didn't notice something was missing.

**Comment by MarijnS95** [comment]
Hi @krolli, thanks for the reply! Let me know when anything needs to change for #17 to land. There have indeed been a few more additions to the spec that would need to be parsed, but `bitwidth` is currently the only one we need to rely on.

It looks like Vulkan-Docs switched from `master` to `main`, the XML on the master branch (that the CI test links to) is stuck at version `152` - that's probably why you didn't get any notifications. Let's see if they show up now: #19.

FWIW same problem here with time, things just keep coming and coming (especially in the open-source space) :sweat_smile:. But do let me know if there's anything we can help out with!

**Comment by MaikKlein** [comment]
> It also doesn't help that github didn't send me any notifications about your pull request or other things.

Btw you have to watch your own crate if you want notifications. I speak from experience :).
![2021-04-22-150004_215x65_scrot](https://user-images.githubusercontent.com/1994306/115718482-6f630f80-a37b-11eb-8de2-5741541aa8da.png)

**Comment by krolli** [comment]
I pushed version 0.6 to crates.io. It should now support everything up to the most recent vk.xml. I wasn't too happy about having phony dependency on log there, so I updated minreq to newer version and bumped minimum rust compiler version to something that would be able to compile it. With compiler update, we can now use `non_exhaustive` attribute on types that mirror vk.xml rnc schema, so we shouldn't need to do major version increases when xml format adds new attributes or members. At this point, I think everything I wanted to have for 1.0 release is in, apart from cleaned up C parser and AST (which I'm not sure is all the useful anyway).

I will probably give it some time (versions 0.7-0.9 probably) to see whether there are still any places that would introduce API breakage when spec is expanded before calling it 1.0 though.

Is there anything else you think we need to resolve as part of this ticket?
