### ISSUE TITLE
Update handling of vendor IDs

### ISSUE THREAD

**Issue by GabrielMajeri** [krolli/vk-parse#8]
In newer versions of the Vulkan API registry, the `vendorid` element has been removed, and vendor IDs are represented by ordinary enums.

Should we remove the `VendorId` structure or keep it for compatibility with older versions of the spec?

**Comment by krolli** [comment]
So far maintaining compatibility with older vk.xml versions didn't require too much extra work, probably because Khronos folks themselves don't break it unless they have a reason to. I like the idea of being compatible with older versions so unless it causes the interface to be more cluttered than necessary, I'd like to maintain that.
